#!/usr/bin/with-contenv bash

if [ ! -f /usr/bin/pip ]; then
  echo "Running Custom installation of Python-Pip and modules"
  apk add --no-cache py2-pip
  pip install --no-cache-dir -U \
    apprise \
    chardet \
    pynzbget
fi
